services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5001:5000" 
    volumes:
      - ./back-end:/back-end-linkup 
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
